language: node_js
cache: yarn
node_js:
  - "node"
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run setup
script:
  # Lint and build all packages
  - standard
  # Run tests and coverage
  - yarn run cover
  # Upload coverage data
  - nyc report --reporter=text-lcov | coveralls
