language: node_js
cache: yarn
node_js:
  - "node"
  - "lts/*"
before_script:
  - yarn run bootstrap
script:
  # Lint and build all packages
  - standard
  - lerna run build
  # Run tests and coverage
  - cd ./packages/uiengine
  - yarn run cover
  # Upload coverage data
  - nyc report --reporter=text-lcov | coveralls
