language: node_js
cache: yarn
node_js:
  - "node"
  - "lts/*"
before_script:
  - yarn run setup
script:
  # Build all packages
  - yarn run build
  # Lint all packages
  - yarn run lint
  # Run tests and coverage
  - yarn run cover
  # Upload coverage data
  - nyc report --reporter=text-lcov | coveralls
